production:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci 
  reconnect: false
  database: database_name
  pool: 5
  timeout: 5000
  username: username
  password: password
  socket: socket